import type { TaskTemplate } from "@/types"

export const defaultPublicTemplates: Omit<TaskTemplate, "id" | "createdAt" | "updatedAt" | "userId">[] = [
  {
    name: "Website Launch Project",
    description: "Complete workflow for launching a new website from planning to deployment",
    category: "Project Management",
    isPublic: true,
    usageCount: 247,
    estimatedDuration: 2880, // 48 hours
    tags: ["website", "launch", "project", "development"],
    tasks: [
      {
        id: "1",
        title: "Define project requirements and scope",
        description: "Document all features, target audience, and technical requirements",
        priority: "high",
        order: 0,
        daysFromStart: 0,
        estimatedTime: 240,
      },
      {
        id: "2",
        title: "Create wireframes and mockups",
        description: "Design the user interface and user experience",
        priority: "high",
        order: 1,
        daysFromStart: 2,
        estimatedTime: 480,
      },
      {
        id: "3",
        title: "Set up development environment",
        description: "Configure local development setup and version control",
        priority: "medium",
        order: 2,
        daysFromStart: 5,
        estimatedTime: 120,
      },
      {
        id: "4",
        title: "Develop frontend components",
        description: "Build reusable UI components and pages",
        priority: "high",
        order: 3,
        daysFromStart: 7,
        estimatedTime: 960,
      },
      {
        id: "5",
        title: "Implement backend functionality",
        description: "Set up APIs, database, and server-side logic",
        priority: "high",
        order: 4,
        daysFromStart: 10,
        estimatedTime: 720,
      },
      {
        id: "6",
        title: "Content creation and copywriting",
        description: "Write all website content, including pages and blog posts",
        priority: "medium",
        order: 5,
        daysFromStart: 14,
        estimatedTime: 360,
      },
      {
        id: "7",
        title: "Testing and quality assurance",
        description: "Test functionality, performance, and cross-browser compatibility",
        priority: "high",
        order: 6,
        daysFromStart: 18,
        estimatedTime: 240,
      },
      {
        id: "8",
        title: "SEO optimization",
        description: "Optimize for search engines and implement analytics",
        priority: "medium",
        order: 7,
        daysFromStart: 20,
        estimatedTime: 180,
      },
      {
        id: "9",
        title: "Deploy to production",
        description: "Set up hosting, domain, and deploy the website",
        priority: "high",
        order: 8,
        daysFromStart: 22,
        estimatedTime: 120,
      },
      {
        id: "10",
        title: "Launch announcement and marketing",
        description: "Announce the launch on social media and marketing channels",
        priority: "medium",
        order: 9,
        daysFromStart: 23,
        estimatedTime: 90,
      },
    ],
  },
  {
    name: "Social Media Campaign",
    description: "Complete social media marketing campaign from strategy to execution",
    category: "Marketing",
    isPublic: true,
    usageCount: 189,
    estimatedDuration: 720, // 12 hours
    tags: ["social media", "marketing", "campaign", "content"],
    tasks: [
      {
        id: "1",
        title: "Define campaign goals and KPIs",
        description: "Set clear objectives and success metrics for the campaign",
        priority: "high",
        order: 0,
        daysFromStart: 0,
        estimatedTime: 60,
      },
      {
        id: "2",
        title: "Research target audience",
        description: "Analyze demographics, interests, and behavior patterns",
        priority: "high",
        order: 1,
        daysFromStart: 1,
        estimatedTime: 120,
      },
      {
        id: "3",
        title: "Competitor analysis",
        description: "Study competitor strategies and identify opportunities",
        priority: "medium",
        order: 2,
        daysFromStart: 2,
        estimatedTime: 90,
      },
      {
        id: "4",
        title: "Create content calendar",
        description: "Plan posting schedule and content themes for each platform",
        priority: "high",
        order: 3,
        daysFromStart: 3,
        estimatedTime: 120,
      },
      {
        id: "5",
        title: "Design visual assets",
        description: "Create graphics, videos, and other visual content",
        priority: "high",
        order: 4,
        daysFromStart: 5,
        estimatedTime: 240,
      },
      {
        id: "6",
        title: "Write copy and captions",
        description: "Create engaging text content for all posts",
        priority: "medium",
        order: 5,
        daysFromStart: 7,
        estimatedTime: 180,
      },
      {
        id: "7",
        title: "Set up tracking and analytics",
        description: "Configure UTM parameters and tracking tools",
        priority: "medium",
        order: 6,
        daysFromStart: 9,
        estimatedTime: 60,
      },
      {
        id: "8",
        title: "Launch campaign",
        description: "Begin posting content according to the schedule",
        priority: "high",
        order: 7,
        daysFromStart: 10,
        estimatedTime: 30,
      },
      {
        id: "9",
        title: "Monitor and engage",
        description: "Respond to comments and monitor campaign performance",
        priority: "medium",
        order: 8,
        daysFromStart: 10,
        estimatedTime: 60,
      },
      {
        id: "10",
        title: "Analyze results and report",
        description: "Compile performance data and create final report",
        priority: "medium",
        order: 9,
        daysFromStart: 17,
        estimatedTime: 120,
      },
    ],
  },
  {
    name: "Mobile App Development",
    description: "End-to-end mobile app development process from concept to app store",
    category: "Development",
    isPublic: true,
    usageCount: 156,
    estimatedDuration: 4320, // 72 hours
    tags: ["mobile", "app", "development", "ios", "android"],
    tasks: [
      {
        id: "1",
        title: "Market research and validation",
        description: "Research market demand and validate app concept",
        priority: "high",
        order: 0,
        daysFromStart: 0,
        estimatedTime: 240,
      },
      {
        id: "2",
        title: "Define app features and user stories",
        description: "Create detailed feature specifications and user journey maps",
        priority: "high",
        order: 1,
        daysFromStart: 3,
        estimatedTime: 360,
      },
      {
        id: "3",
        title: "Create app wireframes",
        description: "Design the app's structure and navigation flow",
        priority: "high",
        order: 2,
        daysFromStart: 7,
        estimatedTime: 480,
      },
      {
        id: "4",
        title: "Design UI/UX mockups",
        description: "Create high-fidelity designs for all app screens",
        priority: "high",
        order: 3,
        daysFromStart: 12,
        estimatedTime: 720,
      },
      {
        id: "5",
        title: "Set up development environment",
        description: "Configure development tools, frameworks, and CI/CD",
        priority: "medium",
        order: 4,
        daysFromStart: 18,
        estimatedTime: 180,
      },
      {
        id: "6",
        title: "Develop core functionality",
        description: "Build the main features and business logic",
        priority: "high",
        order: 5,
        daysFromStart: 21,
        estimatedTime: 1440,
      },
      {
        id: "7",
        title: "Implement user authentication",
        description: "Add login, registration, and security features",
        priority: "high",
        order: 6,
        daysFromStart: 35,
        estimatedTime: 360,
      },
      {
        id: "8",
        title: "Integrate third-party services",
        description: "Connect APIs, payment systems, and analytics",
        priority: "medium",
        order: 7,
        daysFromStart: 42,
        estimatedTime: 480,
      },
      {
        id: "9",
        title: "Testing and debugging",
        description: "Comprehensive testing on multiple devices and platforms",
        priority: "high",
        order: 8,
        daysFromStart: 49,
        estimatedTime: 720,
      },
      {
        id: "10",
        title: "App store preparation",
        description: "Create store listings, screenshots, and submit for review",
        priority: "medium",
        order: 9,
        daysFromStart: 56,
        estimatedTime: 240,
      },
    ],
  },
  {
    name: "Event Planning Checklist",
    description: "Complete checklist for organizing successful events from start to finish",
    category: "Event Planning",
    isPublic: true,
    usageCount: 312,
    estimatedDuration: 1200, // 20 hours
    tags: ["event", "planning", "organization", "checklist"],
    tasks: [
      {
        id: "1",
        title: "Define event objectives and budget",
        description: "Set clear goals, target audience, and financial constraints",
        priority: "high",
        order: 0,
        daysFromStart: 0,
        estimatedTime: 120,
      },
      {
        id: "2",
        title: "Choose event date and venue",
        description: "Research and book the perfect location for your event",
        priority: "high",
        order: 1,
        daysFromStart: 2,
        estimatedTime: 180,
      },
      {
        id: "3",
        title: "Create guest list and send invitations",
        description: "Compile attendee list and send out invitations",
        priority: "high",
        order: 2,
        daysFromStart: 7,
        estimatedTime: 120,
      },
      {
        id: "4",
        title: "Plan catering and menu",
        description: "Arrange food and beverage services for the event",
        priority: "medium",
        order: 3,
        daysFromStart: 10,
        estimatedTime: 150,
      },
      {
        id: "5",
        title: "Arrange entertainment and speakers",
        description: "Book performers, speakers, or entertainment for the event",
        priority: "medium",
        order: 4,
        daysFromStart: 14,
        estimatedTime: 180,
      },
      {
        id: "6",
        title: "Design and order promotional materials",
        description: "Create banners, programs, and other branded materials",
        priority: "low",
        order: 5,
        daysFromStart: 18,
        estimatedTime: 120,
      },
      {
        id: "7",
        title: "Coordinate logistics and setup",
        description: "Plan equipment, seating, and technical requirements",
        priority: "high",
        order: 6,
        daysFromStart: 21,
        estimatedTime: 240,
      },
      {
        id: "8",
        title: "Confirm all vendors and suppliers",
        description: "Double-check all bookings and arrangements",
        priority: "high",
        order: 7,
        daysFromStart: 26,
        estimatedTime: 90,
      },
      {
        id: "9",
        title: "Event day execution",
        description: "Oversee the event and ensure everything runs smoothly",
        priority: "high",
        order: 8,
        daysFromStart: 30,
        estimatedTime: 480,
      },
      {
        id: "10",
        title: "Post-event follow-up and evaluation",
        description: "Send thank you notes and gather feedback",
        priority: "low",
        order: 9,
        daysFromStart: 32,
        estimatedTime: 90,
      },
    ],
  },
  {
    name: "Content Creation Workflow",
    description: "Streamlined process for creating high-quality content from ideation to publication",
    category: "Content Creation",
    isPublic: true,
    usageCount: 203,
    estimatedDuration: 480, // 8 hours
    tags: ["content", "writing", "blog", "creation", "publishing"],
    tasks: [
      {
        id: "1",
        title: "Brainstorm content ideas",
        description: "Generate and research potential topics and angles",
        priority: "medium",
        order: 0,
        daysFromStart: 0,
        estimatedTime: 60,
      },
      {
        id: "2",
        title: "Keyword research and SEO planning",
        description: "Research target keywords and plan SEO strategy",
        priority: "medium",
        order: 1,
        daysFromStart: 1,
        estimatedTime: 90,
      },
      {
        id: "3",
        title: "Create content outline",
        description: "Structure the content with headings and key points",
        priority: "high",
        order: 2,
        daysFromStart: 2,
        estimatedTime: 45,
      },
      {
        id: "4",
        title: "Write first draft",
        description: "Create the initial version of the content",
        priority: "high",
        order: 3,
        daysFromStart: 3,
        estimatedTime: 180,
      },
      {
        id: "5",
        title: "Source and create visuals",
        description: "Find or create images, graphics, and other visual elements",
        priority: "medium",
        order: 4,
        daysFromStart: 5,
        estimatedTime: 120,
      },
      {
        id: "6",
        title: "Edit and proofread",
        description: "Review content for grammar, clarity, and flow",
        priority: "high",
        order: 5,
        daysFromStart: 7,
        estimatedTime: 90,
      },
      {
        id: "7",
        title: "Optimize for SEO",
        description: "Add meta descriptions, alt text, and optimize keywords",
        priority: "medium",
        order: 6,
        daysFromStart: 8,
        estimatedTime: 45,
      },
      {
        id: "8",
        title: "Format and publish",
        description: "Format the content and publish on the platform",
        priority: "high",
        order: 7,
        daysFromStart: 9,
        estimatedTime: 60,
      },
      {
        id: "9",
        title: "Promote on social media",
        description: "Share the content across social media channels",
        priority: "low",
        order: 8,
        daysFromStart: 10,
        estimatedTime: 30,
      },
      {
        id: "10",
        title: "Monitor performance and engagement",
        description: "Track views, engagement, and gather feedback",
        priority: "low",
        order: 9,
        daysFromStart: 14,
        estimatedTime: 30,
      },
    ],
  },
  {
    name: "Job Interview Preparation",
    description: "Comprehensive preparation guide for job interviews",
    category: "Personal",
    isPublic: true,
    usageCount: 428,
    estimatedDuration: 360, // 6 hours
    tags: ["interview", "job", "career", "preparation"],
    tasks: [
      {
        id: "1",
        title: "Research the company and role",
        description: "Study company culture, values, and job requirements",
        priority: "high",
        order: 0,
        daysFromStart: 0,
        estimatedTime: 90,
      },
      {
        id: "2",
        title: "Review and update resume",
        description: "Ensure resume is current and tailored to the position",
        priority: "high",
        order: 1,
        daysFromStart: 1,
        estimatedTime: 60,
      },
      {
        id: "3",
        title: "Prepare answers to common questions",
        description: "Practice responses to typical interview questions",
        priority: "high",
        order: 2,
        daysFromStart: 2,
        estimatedTime: 120,
      },
      {
        id: "4",
        title: "Prepare questions to ask interviewer",
        description: "Develop thoughtful questions about the role and company",
        priority: "medium",
        order: 3,
        daysFromStart: 3,
        estimatedTime: 30,
      },
      {
        id: "5",
        title: "Practice with mock interviews",
        description: "Conduct practice interviews with friends or family",
        priority: "medium",
        order: 4,
        daysFromStart: 4,
        estimatedTime: 60,
      },
      {
        id: "6",
        title: "Plan interview outfit",
        description: "Choose and prepare appropriate professional attire",
        priority: "low",
        order: 5,
        daysFromStart: 5,
        estimatedTime: 30,
      },
      {
        id: "7",
        title: "Prepare portfolio or work samples",
        description: "Organize examples of your work to showcase",
        priority: "medium",
        order: 6,
        daysFromStart: 6,
        estimatedTime: 45,
      },
      {
        id: "8",
        title: "Plan route and timing",
        description: "Research location and plan arrival time",
        priority: "medium",
        order: 7,
        daysFromStart: 7,
        estimatedTime: 15,
      },
      {
        id: "9",
        title: "Final preparation and relaxation",
        description: "Review notes and practice relaxation techniques",
        priority: "low",
        order: 8,
        daysFromStart: 7,
        estimatedTime: 30,
      },
    ],
  },
  {
    name: "Product Launch Strategy",
    description: "Complete product launch plan from pre-launch to post-launch activities",
    category: "Business",
    isPublic: true,
    usageCount: 167,
    estimatedDuration: 1800, // 30 hours
    tags: ["product", "launch", "marketing", "strategy", "business"],
    tasks: [
      {
        id: "1",
        title: "Market analysis and positioning",
        description: "Analyze target market and define product positioning",
        priority: "high",
        order: 0,
        daysFromStart: 0,
        estimatedTime: 240,
      },
      {
        id: "2",
        title: "Develop pricing strategy",
        description: "Research competitors and set optimal pricing",
        priority: "high",
        order: 1,
        daysFromStart: 3,
        estimatedTime: 180,
      },
      {
        id: "3",
        title: "Create launch timeline",
        description: "Plan detailed timeline with milestones and deadlines",
        priority: "high",
        order: 2,
        daysFromStart: 7,
        estimatedTime: 120,
      },
      {
        id: "4",
        title: "Develop marketing materials",
        description: "Create brochures, website content, and promotional materials",
        priority: "medium",
        order: 3,
        daysFromStart: 10,
        estimatedTime: 360,
      },
      {
        id: "5",
        title: "Build pre-launch buzz",
        description: "Start teaser campaigns and build anticipation",
        priority: "medium",
        order: 4,
        daysFromStart: 21,
        estimatedTime: 240,
      },
      {
        id: "6",
        title: "Train sales and support teams",
        description: "Educate teams on product features and benefits",
        priority: "high",
        order: 5,
        daysFromStart: 28,
        estimatedTime: 180,
      },
      {
        id: "7",
        title: "Set up distribution channels",
        description: "Establish partnerships and distribution networks",
        priority: "high",
        order: 6,
        daysFromStart: 35,
        estimatedTime: 240,
      },
      {
        id: "8",
        title: "Execute launch campaign",
        description: "Launch the product with coordinated marketing efforts",
        priority: "high",
        order: 7,
        daysFromStart: 42,
        estimatedTime: 120,
      },
      {
        id: "9",
        title: "Monitor launch metrics",
        description: "Track sales, feedback, and performance indicators",
        priority: "medium",
        order: 8,
        daysFromStart: 43,
        estimatedTime: 60,
      },
      {
        id: "10",
        title: "Post-launch optimization",
        description: "Analyze results and optimize based on feedback",
        priority: "medium",
        order: 9,
        daysFromStart: 49,
        estimatedTime: 180,
      },
    ],
  },
  {
    name: "Online Course Creation",
    description: "Step-by-step guide to creating and launching an online course",
    category: "Education",
    isPublic: true,
    usageCount: 134,
    estimatedDuration: 2400, // 40 hours
    tags: ["course", "education", "online", "teaching", "content"],
    tasks: [
      {
        id: "1",
        title: "Define course topic and audience",
        description: "Choose subject matter and identify target learners",
        priority: "high",
        order: 0,
        daysFromStart: 0,
        estimatedTime: 120,
      },
      {
        id: "2",
        title: "Research and validate course idea",
        description: "Ensure there's demand for your course topic",
        priority: "high",
        order: 1,
        daysFromStart: 2,
        estimatedTime: 180,
      },
      {
        id: "3",
        title: "Create course outline and curriculum",
        description: "Structure lessons and learning objectives",
        priority: "high",
        order: 2,
        daysFromStart: 5,
        estimatedTime: 240,
      },
      {
        id: "4",
        title: "Write course scripts and materials",
        description: "Develop detailed content for each lesson",
        priority: "high",
        order: 3,
        daysFromStart: 10,
        estimatedTime: 720,
      },
      {
        id: "5",
        title: "Record video lessons",
        description: "Film all course content with good audio and video quality",
        priority: "high",
        order: 4,
        daysFromStart: 25,
        estimatedTime: 960,
      },
      {
        id: "6",
        title: "Edit and produce videos",
        description: "Edit footage, add graphics, and enhance audio",
        priority: "medium",
        order: 5,
        daysFromStart: 40,
        estimatedTime: 480,
      },
      {
        id: "7",
        title: "Create supplementary materials",
        description: "Develop worksheets, quizzes, and downloadable resources",
        priority: "medium",
        order: 6,
        daysFromStart: 48,
        estimatedTime: 240,
      },
      {
        id: "8",
        title: "Set up course platform",
        description: "Upload content to learning management system",
        priority: "medium",
        order: 7,
        daysFromStart: 54,
        estimatedTime: 120,
      },
      {
        id: "9",
        title: "Create marketing and sales pages",
        description: "Develop compelling course descriptions and landing pages",
        priority: "medium",
        order: 8,
        daysFromStart: 58,
        estimatedTime: 180,
      },
      {
        id: "10",
        title: "Launch and promote course",
        description: "Release course and execute marketing strategy",
        priority: "high",
        order: 9,
        daysFromStart: 63,
        estimatedTime: 120,
      },
    ],
  },
]
